/**
 *  VANISHING POINTS — GEODETIC DATABASE CONSOLIDATION UTILITY
 *  This script merges the duplicate Beelitz hospital pylons into a single canonical 
 *  case file ('beelitz-surgery-basement') to prevent overlapping cartographic markers 
 *  on the AtlasMap, and standardizes all geodetic connections symmetrically.
 * 
 *  To run: node consolidate-beelitz.js
 */

const fs = require('fs');
const path = require('path');

const possiblePaths = [
  path.join(process.cwd(), 'scripts', 'mapped-places.json'),
  path.join(process.cwd(), 'scripts', 'mapped-places-clean.json'),
  path.join(process.cwd(), 'mapped-places.json'),
  path.join(process.cwd(), 'data', 'mapped-places.json')
];

let targetFile = null;
let rawData = null;

for (const p of possiblePaths) {
  if (fs.existsSync(p)) {
    targetFile = p;
    rawData = fs.readFileSync(p, 'utf-8');
    console.log(`[Database Cleaner] Found master geodetic pylon database at: ${p}`);
    break;
  }
}

if (!rawData) {
  console.error('[Database Cleaner] Error: Master "mapped-places.json" dataset not found in standard paths.');
  console.log('Please copy this script into your Next.js project root and run: node consolidate-beelitz.js');
  process.exit(1);
}

try {
  let parsed = JSON.parse(rawData);
  let isWrapper = false;
  let places = [];

  if (Array.isArray(parsed)) {
    places = parsed;
  } else if (parsed && Array.isArray(parsed.places)) {
    places = parsed.places;
    isWrapper = true;
  } else {
    throw new Error('Unsupported database structure');
  }

  const initialCount = places.length;
  console.log(`[Database Cleaner] Mapped Places Database loaded. Initial size: ${initialCount} pylons.`);

  // 1. Locate the Beelitz surgical basement (authoritative) and Beelitz sanatorium (duplicate)
  const canonicalSlug = 'beelitz-surgery-basement';
  const duplicateSlug = 'beelitz-heilsttten';

  const canonicalPlace = places.find(p => p.slug === canonicalSlug);
  const duplicatePlace = places.find(p => p.slug === duplicateSlug);

  if (!canonicalPlace) {
    console.warn(`[Database Cleaner] Warning: Could not find canonical pylon "${canonicalSlug}" in database.`);
  }

  if (duplicatePlace) {
    console.log(`[Database Cleaner] Merging duplicate "${duplicateSlug}" into "${canonicalSlug}"...`);

    // Symmetrically consolidate connectedTo arrays
    if (canonicalPlace) {
      const mergedConnections = new Set([
        ...(canonicalPlace.connectedTo || []),
        ...(duplicatePlace.connectedTo || [])
      ]);
      // Remove self-references
      mergedConnections.delete(canonicalSlug);
      mergedConnections.delete(duplicateSlug);
      canonicalPlace.connectedTo = Array.from(mergedConnections);

      console.log(`[Database Cleaner] Updated connections for "${canonicalSlug}": [${canonicalPlace.connectedTo.join(', ')}]`);
    }

    // 2. Remove the duplicate Beelitz pylon
    places = places.filter(p => p.slug !== duplicateSlug);
    console.log(`[Database Cleaner] Purged duplicate "${duplicateSlug}" from map registry.`);
  } else {
    console.log(`[Database Cleaner] Duplicate pylon "${duplicateSlug}" was already removed or is not present.`);
  }

  // 3. Symmetrically standardize all connections in other places pointing to the duplicate
  let connectionsReroutedCount = 0;
  places = places.map(place => {
    if (place.connectedTo && Array.isArray(place.connectedTo)) {
      const hasConnection = place.connectedTo.includes(duplicateSlug);
      if (hasConnection) {
        // Replace with canonical and deduplicate
        const updatedSet = new Set(place.connectedTo.map(c => c === duplicateSlug ? canonicalSlug : c));
        // Prevent self-routing loops
        updatedSet.delete(place.slug);
        place.connectedTo = Array.from(updatedSet);
        connectionsReroutedCount++;
      }
    }
    return place;
  });

  console.log(`[Database Cleaner] Re-routed ${connectionsReroutedCount} connections pointing to "${duplicateSlug}" symmetrically.`);

  // Save the standardized places JSON
  const outputJson = isWrapper ? { ...parsed, places } : places;
  fs.writeFileSync(targetFile, JSON.stringify(outputJson, null, 2), 'utf-8');
  console.log(`[Database Cleaner] Successfully written standardized database back to: ${targetFile}`);

  // 4. Symmetrically generate/update data/places.ts to keep the build aligned
  const placesTsPath = path.join(process.cwd(), 'data', 'places.ts');
  if (fs.existsSync(placesTsPath)) {
    console.log(`[Database Cleaner] Aligned seed places file found at: ${placesTsPath}. Updating...`);
    const tsContent = `import { Place } from "@/types/places";

/**
 *  AUTOMATICALLY COMPILED GEODETIC ATLAS CORPUS
 *  Generated by consolidate-beelitz.js -- aligned symmetrically to prevent coordinate duplicate drift.
 */
export const LOCAL_PLACES: Place[] = ${JSON.stringify(places, null, 2)};

export async function fetchPlaces(): Promise<Place[]> {
  try {
    const res = await fetch('/api/places');
    if (!res.ok) throw new Error('Archive unreachable');
    const data = await res.json();
    if (!Array.isArray(data)) throw new Error('Invalid archive format');
    return data as Place[];
  } catch (err) {
    console.warn('[Atlas] Remote database unreachable. Reverting to local static seed.');
    return LOCAL_PLACES;
  }
}
`;
    fs.writeFileSync(placesTsPath, tsContent, 'utf-8');
    console.log(`[Database Cleaner] Successfully synchronized: ${placesTsPath}`);
  }

  console.log(`\n[Database Cleaner] Database consolidation complete. Mapped cases reduced from ${initialCount} to ${places.length}.`);
  console.log('--------------------------------------------------------------------------------------\n');

} catch (e) {
  console.error('[Database Cleaner] Compilation/Parsing failed during standardisation loop:', e.message);
}
